### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by rspsgallus** [Mige5/rs2006sp#34]
java.lang.ArrayIndexOutOfBoundsException: -1
        at com.rs2.model.d.f.aY(Unknown Source)
        at com.rs2.model.d.h.a(Unknown Source)
        at com.rs2.model.f.b.a(Unknown Source)
        at com.rs2.model.f.c.b(Unknown Source)
        at com.rs2.model.h.a(Unknown Source)
        at com.rs2.Server.B(Unknown Source)
        at com.rs2.Server.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)

**Comment by rspsgallus** [comment]
https://pastebin.com/9DG0XsJx
