### ISSUE TITLE
Ran out of arrows and was hit while picking them up, gave an error.

### ISSUE THREAD

**Issue by NeedingName** [Mige5/rs2006sp#37]
java.lang.NullPointerException
        at com.rs2.model.a.a.f.a(Unknown Source)
        at com.rs2.model.c.i.e(Unknown Source)
        at com.rs2.model.a.a.f.a(Unknown Source)
        at com.rs2.model.f.d.i(Unknown Source)
        at com.rs2.model.h.a(Unknown Source)
        at com.rs2.Server.B(Unknown Source)
        at com.rs2.Server.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Started a new account and had this error as I ran out of arrows on an imp, I picked them up and was attacked which completely froze my character and made that error spam in the cmd window. I use the latest Patreon version with hd patch, I tested a few times and it always happens when I am attacked without arrows equipped while wielding a bow, I did not test without hd patch.

**Comment by Mige5** [comment]
weird, I attempted this several times now and wasnt able to cause any errors.

**Comment by NeedingName** [comment]
I probably messed up something with the hdmod then... I disabled it in the settings and no more issues.

**Comment by Mige5** [comment]
Finally managed to cause an error with this, fixed on next update.
