### ISSUE TITLE
Server never starts up

### ISSUE THREAD

**Issue by gnubyte** [Mige5/rs2006sp#38]
Server isn't starting up. Followed readme

```
C:\Users\REMOVED\Downloads\2006 Singleplayer v3.0 (patreon)\Server>java -Xmx1024m -jar "Server".jar
[7/25/20 8:55 AM]: Starting RuneScape on /0.0.0.0:43594...
com.rs2.b.b: No index files present.
        at com.rs2.b.a.<init>(Unknown Source)
        at com.rs2.b.a.a(Unknown Source)
        at com.rs2.Server.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at com.rs2.model.d.b.b.a(Unknown Source)
        at com.rs2.Server.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

```

**Comment by Mige5** [comment]
Follow update guide in discord.
